apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  student-server.conf: |
    server {
        listen         80 default_server;

        location / {
            return 200 'Hello мир, Манера крутит мир!';
        }
    }
